spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sttest?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  graphql:
    graphiql:
      enabled: true # web browser 접속
    schema:
      printer:
        enabled: true #graphql 콘솔 출력